# Generated by Django 5.2.5 on 2025-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_waiter_item_image_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, choices=[('chica', 'Chica'), ('mediana', 'Mediana'), ('grande', 'Grande')], max_length=10),
        ),
    ]
